const actionTypes =  {
		LOGIN_SUCESSFUL: "LOGIN_SUCESSFUL", 
		LOGIN_NOT_SUCESSFUL: "LOGIN_NOT_SUCESSFUL",
		NEW_USER: "NEW_USER", 
		SUBMIT: "SUBMIT",
		PARTY_DATA: "PARTY_DATA", 
		GET_PARTY_DATA: "GET_PARTY_DATA",
		GET_STATUS: "GET_STATUS", 
		GET_PARTY_BY_ID: "GET_PARTY_BY_ID"
};

export default actionTypes;
